# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SteamList' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SteamList

  target 'SteamListTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SteamListUITests' do
    # Pods for testing
  end

end
